
'use client';

import { useState, useMemo } from 'react';
import type {Metadata} from 'next';
import './globals.css';
import { Toaster } from "@/components/ui/toaster";
import { SidebarProvider, Sidebar, SidebarInset, SidebarContent, SidebarHeader, SidebarFooter, SidebarInput } from '@/components/ui/sidebar';
import { tasks, Task } from '@/lib/tasks';

// export const metadata: Metadata = {
//   title: 'Tax Advisory Platform',
//   description: 'Generated by Firebase Studio',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [searchQuery, setSearchQuery] = useState('');

  const filteredTasks = useMemo(() => {
    if (!searchQuery) {
      return [];
    }
    return tasks.filter((task) =>
      task.customerName.toLowerCase().includes(searchQuery.toLowerCase())
    );
  }, [searchQuery]);

  return (
    <html lang="en">
      <head>
        <title>Tax Advisory Platform</title>
        <meta name="description" content="Generated by Firebase Studio" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap" rel="stylesheet" />
      </head>
      <body className="antialiased">
        <SidebarProvider defaultOpen={false}>
          <Sidebar>
            <SidebarHeader>
              {/* Sidebar Header Content */}
            </SidebarHeader>
            <SidebarContent>
              <div className="p-2 mt-8">
                <SidebarInput 
                  placeholder="Search..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                />
                 {filteredTasks.length > 0 && (
                  <div className="mt-4">
                    <h2 className="text-xs font-semibold text-muted-foreground px-2">Companies</h2>
                    <ul className="mt-2 space-y-1">
                      {filteredTasks.map((task) => (
                        <li
                          key={task.id}
                          className="text-sm p-2 rounded-md hover:bg-muted cursor-pointer"
                        >
                          {task.customerName}
                        </li>
                      ))}
                    </ul>
                  </div>
                )}
              </div>
              {/* Sidebar Main Content */}
            </SidebarContent>
            <SidebarFooter>
              {/* Sidebar Footer Content */}
            </SidebarFooter>
          </Sidebar>
          <SidebarInset>
            {children}
            <Toaster />
          </SidebarInset>
        </SidebarProvider>
      </body>
    </html>
  );
}
