import type {Metadata} from 'next';
import './globals.css';
import { Toaster } from "@/components/ui/toaster";
import { SidebarProvider, Sidebar, SidebarInset, SidebarContent, SidebarHeader, SidebarFooter, SidebarInput } from '@/components/ui/sidebar';

export const metadata: Metadata = {
  title: 'Tax Advisory Platform',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap" rel="stylesheet" />
      </head>
      <body className="antialiased">
        <SidebarProvider>
          <Sidebar>
            <SidebarHeader>
              {/* Sidebar Header Content */}
            </SidebarHeader>
            <SidebarContent>
              <div className="p-2">
                <SidebarInput placeholder="Search..." />
              </div>
              {/* Sidebar Main Content */}
            </SidebarContent>
            <SidebarFooter>
              {/* Sidebar Footer Content */}
            </SidebarFooter>
          </Sidebar>
          <SidebarInset>
            {children}
            <Toaster />
          </SidebarInset>
        </SidebarProvider>
      </body>
    </html>
  );
}
